BicycleApplication/Controllers/BicycleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Repository;
using Contracts;
using Entities.Models;
using Service.Contracts;
using Shared.DataTransferObjects;
using Shared.Filters;
using Shared.ViewModels;

namespace BicycleApplication.Controllers
{
    public class BicycleController : Controller
    {
        private readonly IServiceManager<Bicycle> _service;

        public BicycleController(IServiceManager<Bicycle> service)
        {
            _service = service;
        }

        public IActionResult Index(string sortOrder)
        {
            var bicycles = _service.BicycleService.GetAllBicycles();
            //Max price value for ranger
            ViewBag.MaxPriceValue = bicycles.Any() ? Convert.ToInt32(bicycles.Max(m => m.Price)) : 0;

            //Sort by parameter
            var bicyclesDto = bicycles.Select(m => new BicycleDto(m)).ToList();

            SetSortOrderViewBags(sortOrder);
            bicyclesDto = SortBicycles(bicyclesDto, sortOrder);

            var bicycleViewModel = CreateBicycleViewModel(bicyclesDto);

            return View(bicycleViewModel);
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult Index(string searchString, int min, int max,
            List<ColorFilter> colorFilter,
            List<WheelFilter> wheelFilter,
            List<YearFilter> yearFilter,
            List<FrameFilter> frameFilter,
            List<PedantFilter> pedantFilter,
            List<BrakeFilter> brakeFilter)
        {
            var bicycles = _service.BicycleService.GetAllBicycles().ToList();

            // Max price value for ranger
            ViewBag.MaxPriceValue = bicycles.Any() ? Convert.ToInt32(bicycles.Max(m => m.Price)) : 0;

            // Search by price
            if (max > 0)
            {
                bicycles = bicycles.Where(m => m.Price >= min && m.Price <= max).ToList();
            }

            // Search by model name
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                bicycles = bicycles.Where(m => m.Name.ToLower().Contains(searchString)).ToList();
            }

            // Search by filters
            bicycles = _service.FiltersService.Filter(bicycles, colorFilter, yearFilter, wheelFilter);

            var bicyclesDto = bicycles.Select(m => new BicycleDto(m)).ToList();
            var bicycleViewModel = CreateBicycleViewModel(bicyclesDto);

            return View(bicycleViewModel);
        }

        private void SetSortOrderViewBags(string sortOrder)
        {
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "Name" : "name_desc";
            ViewBag.ColorSortParm = string.IsNullOrEmpty(sortOrder) ? "Color" : "color_desc";
            ViewBag.YearSortParm = string.IsNullOrEmpty(sortOrder) ? "Year" : "year_desc";
            ViewBag.FrameSortParm = string.IsNullOrEmpty(sortOrder) ? "Frame" : "frame_desc";
            ViewBag.PedantSortParm = string.IsNullOrEmpty(sortOrder) ? "Pedant" : "pedant_desc";
            ViewBag.BrakeSortParm = string.IsNullOrEmpty(sortOrder) ? "Brake" : "brake_desc";
            ViewBag.PriceSortParm = string.IsNullOrEmpty(sortOrder) ? "Price" : "price_desc";
        }

        private List<BicycleDto> SortBicycles(List<BicycleDto> bicycles, string sortOrder)
        {
            return sortOrder switch
            {
                "name_desc" => bicycles.OrderBy(s => s.Name).ToList(),
                "color_desc" => bicycles.OrderBy(s => s.Color).ToList(),
                "year_desc" => bicycles.OrderBy(s => s.Year).ToList(),
                "frame_desc" => bicycles.OrderBy(s => s.FrameMaterial).ToList(),
                "pedant_desc" => bicycles.OrderBy(s => s.PedantType).ToList(),
                "brake_desc" => bicycles.OrderBy(s => s.BrakeType).ToList(),
                "price_desc" => bicycles.OrderBy(s => s.Price).ToList(),
                _ => bicycles
            };
        }

        private BicycleViewModel CreateBicycleViewModel(List<BicycleDto> bicycles)
        {
            return new BicycleViewModel()
            {
                Bicycles = bicycles,
                ColorFilter = _service.FiltersService.GetColors().ToList(),
                WheelFilter = _service.FiltersService.GetWheels().ToList(),
                YearFilter = _service.FiltersService.GetYears().ToList()
            };
        }
    }
}

BicycleApplication/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BicycleApplication.Controllers
{
    public class CategoryController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

BicycleApplication/Controllers/CompareCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BicycleApplication.Extensions;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Service.Contracts;

namespace BicycleApplication.Controllers
{
    public class CompareCartController : Controller
    {
        private readonly IBicycleService<Bicycle> _bicycleService;

        public CompareCartController(IBicycleService<Bicycle> bicycleService)
        {
            _bicycleService = bicycleService;
        }

        public IActionResult Index()
        {
            var compareCart = HttpContext.Session.Get<List<CompareItem>>("compare") ?? new List<CompareItem>();
            return View(compareCart);
        }

        public IActionResult Compare(int id)
        {
            var bicycle = _bicycleService.GetBicycle(id);
            var compareCart = HttpContext.Session.Get<List<CompareItem>>("compare") ?? new List<CompareItem>();

            if (!compareCart.Any(item => item.Bicycle.Id == id))
            {
                compareCart.Add(new CompareItem { Bicycle = bicycle });
            }

            HttpContext.Session.Set("compare", compareCart);
            return RedirectToAction("Index", "Bicycle");
        }
    }
}

BicycleApplication/Controllers/PurchaseCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BicycleApplication.Extensions;
using Microsoft.AspNetCore.Mvc;
using Service.Contracts;

using Entities.Models;
using Services;

namespace BicycleApplication.Controllers
{
    public class PurchaseCartController : Controller
    {
        private readonly IBicycleService<Bicycle> _service;

        public PurchaseCartController(IBicycleService<Bicycle> service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            var cart = HttpContext.Session.Get<List<BicycleItem>>("cart") ?? new List<BicycleItem>();
            ViewBag.Total = cart.Sum(s => s.Quantity * s.Bicycle.Price);
            return View(cart);
        }

        public IActionResult Add(int id)
        {
            var cart = HttpContext.Session.Get<List<BicycleItem>>("cart") ?? new List<BicycleItem>();
            var index = cart.FindIndex(m => m.Bicycle.Id == id);
            if (index != -1)
            {
                cart[index].Quantity++;
            }
            else
            {
                cart.Add(new BicycleItem { Bicycle = _service.GetBicycle(id), Quantity = 1 });
            }
            HttpContext.Session.Set("cart", cart);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Minus(int id)
        {
            var cart = HttpContext.Session.Get<List<BicycleItem>>("cart") ?? new List<BicycleItem>();
            var index = cart.FindIndex(m => m.Bicycle.Id == id);
            if (index != -1)
            {
                if (cart[index].Quantity > 0)
                {
                    cart[index].Quantity--;
                    if (cart[index].Quantity == 0)
                    {
                        cart.RemoveAt(index);
                    }
                }
            }
            HttpContext.Session.Set("cart", cart);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Buy(int id)
        {
            var bicycle = _service.GetBicycle(id);
            var cart = HttpContext.Session.Get<List<BicycleItem>>("cart");

            if (cart != null)
            {
                var index = cart.FindIndex(m => m.Bicycle.Id == id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new BicycleItem() { Bicycle = bicycle, Quantity = 1 });
                }
            }
            else
            {
                cart = new List<BicycleItem>();
                cart.Add(new BicycleItem() { Bicycle = bicycle, Quantity = 1 });
            }

            HttpContext.Session.Set<List<BicycleItem>>("cart", cart);
            return RedirectToAction("Index", "MountainBicycle");
        }

        public IActionResult Remove(int id)
        {
            var cart = HttpContext.Session.Get<List<BicycleItem>>("cart") ?? new List<BicycleItem>();
            var index = cart.FindIndex(m => m.Bicycle.Id == id);

            if (index != -1)
            {
                cart.RemoveAt(index);
            }

            HttpContext.Session.Set("cart", cart);
            return RedirectToAction(nameof(Index));
        }
    }
}

BicycleApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BicycleApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BicycleApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BicycleApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fas fa-align-left"></i>
                    <span>Меню</span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-align-justify"></i>
                </button>

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bicycle" asp-action="Index">Головна</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Категорії</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PurchaseCart" asp-action="Index">Корзина</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CompareCart" asp-action="Index">Порівняння</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Paper Work - <a asp-area="" asp-controller="" asp-action=""></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BicycleApplication/Views/Shared/_LayoutBicycle.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Collapsible sidebar using Bootstrap 4</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bicycleSite.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BicycleApplication.styles.css" asp-append-version="true" />

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Каталог</h3>
            </div>

            <ul class="list-unstyled components">

                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Велосипеди</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Гірські</a>
                        </li>
                        <li>
                            <a href="#">Шосе</a>
                        </li>
                        <li>
                            <a href="#">Гравійні</a>
                        </li>
                        <li>
                            <a href="#">Електровелосипеди</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">ФІЛЬТР</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            @* <a href="#">Ціна:</a> *@
                            <form asp-controller="Bicycle" asp-action="Index" method="post" class="contactForm">
                                <div class=input-wraper>
                                    <div class="wrapper-price">
                                        <h6>Ціна: </h6>
                                        <div class="price-input">
                                            <div class="field">
                                                @* <span>Min</span> *@
                                                <input type="number" class="input-min" value="2500">
                                            </div>
                                            @* <div class="separator">-</div> *@
                                            <div class="field">
                                                @* <span>Max</span> *@
                                                <input type="number" class="input-max" value="7500">
                                            </div>
                                        </div>
                                        <div class="slider">
                                            <div class="progress"></div>
                                        </div>
                                        <div class="range-input">
                                            <input type="range" class="range-min" min="0" max="10000" value="2500" step="100">
                                            <input type="range" class="range-max" min="0" max="10000" value="7500" step="100">
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </li>
                        <li>
                        </li><!-- Moved the closing </li> tag here -->
                        <li>
                            <a href="#">Шасі</a>
                        </li>
                    </ul>
            </ul>


        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div>
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>


        <!-- jQuery CDN - Slim version (=without AJAX) -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <!-- Popper.JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <!-- Bootstrap JS -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

        <script type="text/javascript">$(document).ready(function () {
                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar').toggleClass('active');
                });
            });

            const rangeInput = document.querySelectorAll(".range-input input"),
                priceInput = document.querySelectorAll(".price-input input"),
                range = document.querySelector(".slider .progress");
            let priceGap = 1000;

            priceInput.forEach(input => {
                input.addEventListener("input", e => {
                    let minPrice = parseInt(priceInput[0].value),
                        maxPrice = parseInt(priceInput[1].value);

                    if ((maxPrice - minPrice >= priceGap) && maxPrice <= rangeInput[1].max) {
                        if (e.target.className === "input-min") {
                            rangeInput[0].value = minPrice;
                            range.style.left = ((minPrice / rangeInput[0].max) * 100) + "%";
                        } else {
                            rangeInput[1].value = maxPrice;
                            range.style.right = 100 - (maxPrice / rangeInput[1].max) * 100 + "%";
                        }
                    }
                });
            });

            rangeInput.forEach(input => {
                input.addEventListener("input", e => {
                    let minVal = parseInt(rangeInput[0].value),
                        maxVal = parseInt(rangeInput[1].value);

                    if ((maxVal - minVal) < priceGap) {
                        if (e.target.className === "range-min") {
                            rangeInput[0].value = maxVal - priceGap
                        } else {
                            rangeInput[1].value = minVal + priceGap;
                        }
                    } else {
                        priceInput[0].value = minVal;
                        priceInput[1].value = maxVal;
                        range.style.left = ((minVal / rangeInput[0].max) * 100) + "%";
                        range.style.right = 100 - (maxVal / rangeInput[1].max) * 100 + "%";
                    }
                });
            });</script>
</body>

</html>