BicycleApplication/Controllers/CharacteristicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BicycleApplication.Controllers
{
    public class CharacteristicController : Controller
    {
        public IActionResult Mountain()
        {
            return View();
        }

        public IActionResult Gravel()
        {
            return View();
        }

        public IActionResult Electro()
        {
            return View();
        }

        public IActionResult Highway()
        {
            return View();
        }
    }
}

BicycleApplication/Controllers/ElectroBicycleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BicycleApplication.Entities.Models;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Service.Contracts;
using Shared.DataTransferObjects;
using Shared.Filters;
using Shared.ViewModels;

namespace BicycleApplication.Controllers
{
    public class ElectroBicycleController : Controller
    {
        private readonly IServiceManager<Bicycle> _mainService;
        private readonly IServiceManager<Electro> _service;

        public ElectroBicycleController(IServiceManager<Bicycle> mainService,
            IServiceManager<Electro> service)
        {
            _mainService = mainService;
            _service = service;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var bicycles = _service.BicycleService.GetAllBicycles().ToList();
            var imagesPath = GetImagePath(bicycles.Count());

            // Max price value for ranger
            ViewBag.MaxPriceValue = bicycles.Any() ? Convert.ToInt32(bicycles.Max(m => m.Price)) : 0;

            var mainBicycles = bicycles.Select(m => new Bicycle(m));
            var electroBicycles = mainBicycles.Select(m => new ElectroDto(m)).ToList();
            var electroViewModel = CreateElectroViewModel(electroBicycles, imagesPath);

            return View(electroViewModel);
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult Index(string searchString, int min, int max,
            List<ColorFilter> colorFilter,
            List<WheelFilter> wheelFilter,
            List<YearFilter> yearFilter,
            List<FrameFilter> frameFilter,
            List<PedantFilter> pedantFilter,
            List<BrakeFilter> brakeFilter)
        {
            var bicycles = _service.BicycleService.GetAllBicycles().ToList();

            // Max price value for ranger
            ViewBag.MaxPriceValue = bicycles.Any() ? bicycles.Max(m => m.Price) : 0;

            // Search by price
            if (max > 0)
            {
                bicycles = bicycles.Where(m => m.Price >= min && m.Price <= max).ToList();
            }

            // Search by model name
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                bicycles = bicycles.Where(m => m.Name.ToLower().Contains(searchString)).ToList();
            }

            // Search by filters
            bicycles = _service.FiltersService.Filter(bicycles, colorFilter, yearFilter, wheelFilter);

            List<string> imagesPath = GetImagePath(bicycles.Count);

            var mainBicycles = bicycles.Select(m => new Bicycle(m));
            var electroBicycle = mainBicycles.Select(m => new ElectroDto(m)).ToList();
            var electroViewModel = CreateElectroViewModel(electroBicycle, imagesPath);

            return View(electroViewModel);
        }

        private ElectroViewModel CreateElectroViewModel(List<ElectroDto> bicycles, List<string> imagePath)
        {
            return new ElectroViewModel()
            {
                Bicycles = bicycles,
                ImagesPath = imagePath,
                ColorFilter = _service.FiltersService.GetColors().ToList(),
                WheelFilter = _service.FiltersService.GetWheels().ToList(),
                YearFilter = _service.FiltersService.GetYears().ToList(),
            };
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Electro bicycle)
        {
            // Define unique Id
            if (bicycle is null)
                throw new Exception();

            bicycle.Id = _mainService.BicycleService.GetAllBicycles().Any() ?
                                        _mainService.BicycleService.GetAllBicycles().Max(m => m.Id) + 1 : 1;

            if (ModelState.IsValid)
            {
                Bicycle mainBicycle = new Bicycle(bicycle, battery: bicycle.Battery, power: bicycle.Power);

                _mainService.BicycleService.CreateBicycle(mainBicycle);
                _service.BicycleService.CreateBicycle(bicycle);

                return RedirectToAction(nameof(Index));
            }

            return View(bicycle);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || _service.BicycleService.GetAllBicycles() == null)
            {
                return NotFound();
            }

            var bicycle = _service.BicycleService.GetAllBicycles().FirstOrDefault(m => m.Id == id);

            if (bicycle == null)
            {
                return NotFound();
            }

            return View(bicycle);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, Electro bicycle)
        {
            if (ModelState.IsValid)
            {
                Bicycle mainBicycle = new Bicycle(bicycle, battery: bicycle.Battery, power: bicycle.Power);
                _mainService.BicycleService.UpdateBicycle(mainBicycle, compTrackChanges: false);
                _service.BicycleService.UpdateBicycle(bicycle, compTrackChanges: false);

                return RedirectToAction(nameof(Index));
            }

            return View(bicycle);
        }

        public IActionResult Details(int? id)
        {
            if (id == null || _service.BicycleService.GetAllBicycles() == null)
            {
                return NotFound();
            }

            var bicycle = _service.BicycleService.GetAllBicycles().FirstOrDefault(m => m.Id == id);

            if (bicycle == null)
            {
                return NotFound();
            }

            return View(bicycle);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || _service.BicycleService.GetAllBicycles() == null)
            {
                return NotFound();
            }

            var bicycle = _service.BicycleService.GetAllBicycles().FirstOrDefault(m => m.Id == id);

            if (bicycle == null)
            {
                return NotFound();
            }

            return View(bicycle);
        }

        [HttpPost, ActionName("Delete")]
        [IgnoreAntiforgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (_service.BicycleService.GetAllBicycles() == null)
            {
                return Problem("Entity set 'BicycleContext.Bicycle' is null");
            }

            _service.BicycleService.DeleteBicycle(id);
            _mainService.BicycleService.DeleteBicycle(id);

            return RedirectToAction(nameof(Index));
        }

        private static List<string> GetImagePath(int amount)
        {
            List<string> imagesPath = new List<string>();

            for (int i = 0; i < amount; i++)
            {
                int index = (i + 1) % 7;
                imagesPath.Add($"~/Images/electro{index}.png");
            }

            return imagesPath;
        }
    }
}

BicycleApplication/Controllers/GravelBicycleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BicycleApplication.Entities.Models;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Service.Contracts;
using Shared.DataTransferObjects;
using Shared.Filters;
using Shared.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BicycleApplication.Controllers
{
    public class GravelBicycleController : Controller
    {
        private readonly IServiceManager<Bicycle> _mainService;
        private readonly IServiceManager<Gravel> _service;

        public GravelBicycleController(IServiceManager<Bicycle> mainService,
            IServiceManager<Gravel> service)
        {
            _mainService = mainService;
            _service = service;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var bicycles = _service.BicycleService.GetAllBicycles().ToList();
            var imagesPath = GetImagePath(bicycles.Count());

            // Max price value for ranger
            ViewBag.MaxPriceValue = bicycles.Any() ? Convert.ToInt32(bicycles.Max(m => m.Price)) : 0;

            var mainBicycles = bicycles.Select(m => new Bicycle(m));
            var gravelBicycles = mainBicycles.Select(m => new GravelDto(m)).ToList();
            var gravelViewModel = CreateGravelViewModel(gravelBicycles, imagesPath);

            return View(gravelViewModel);
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult Index(string searchString, int min, int max,
            List<ColorFilter> colorFilter,
            List<WheelFilter> wheelFilter,
            List<YearFilter> yearFilter,
            List<FrameFilter> frameFilter,
            List<PedantFilter> pedantFilter,
            List<BrakeFilter> brakeFilter)
        {
            var bicycles = _service.BicycleService.GetAllBicycles().ToList();

            // Max price value for ranger
            ViewBag.MaxPriceValue = bicycles.Any() ? bicycles.Max(m => m.Price) : 0;

            // Search by price
            if (max > 0)
            {
                bicycles = bicycles.Where(m => m.Price >= min && m.Price <= max).ToList();
            }

            // Search by model name
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                bicycles = bicycles.Where(m => m.Name.ToLower().Contains(searchString)).ToList();
            }

            // Search by filters
            bicycles = _service.FiltersService.Filter(bicycles, colorFilter, yearFilter, wheelFilter);

            List<string> imagesPath = GetImagePath(bicycles.Count);

            var mainBicycles = bicycles.Select(m => new Bicycle(m));
            var gravelBicycle = mainBicycles.Select(m => new GravelDto(m)).ToList();
            var gravelViewModel = CreateGravelViewModel(gravelBicycle, imagesPath);

            return View(gravelViewModel);
        }

        private GravelViewModel CreateGravelViewModel(List<GravelDto> bicycles, List<string> imagePath)
        {
            return new GravelViewModel()
            {
                Bicycles = bicycles,
                ImagesPath = imagePath,
                ColorFilter = _service.FiltersService.GetColors().ToList(),
                WheelFilter = _service.FiltersService.GetWheels().ToList(),
                YearFilter = _service.FiltersService.GetYears().ToList(),
            };
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Gravel bicycle)
        {
            // Define unique Id
            if (bicycle is null)
                throw new Exception();

            bicycle.Id = _mainService.BicycleService.GetAllBicycles().Any() ?
                                        _mainService.BicycleService.GetAllBicycles().Max(m => m.Id) + 1 : 1;

            if (ModelState.IsValid)
            {
                Bicycle mainBicycle = new Bicycle(bicycle, tireWidth: bicycle.TireWidth, handlebarWidth: bicycle.HandlebarWidth);

                _mainService.BicycleService.CreateBicycle(mainBicycle);
                _service.BicycleService.CreateBicycle(bicycle);

                return RedirectToAction(nameof(Index));
            }

            return View(bicycle);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || _service.BicycleService.GetAllBicycles() == null)
            {
                return NotFound();
            }

            var bicycle = _service.BicycleService.GetAllBicycles().FirstOrDefault(m => m.Id == id);

            if (bicycle == null)
            {
                return NotFound();
            }

            return View(bicycle);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, Gravel bicycle)
        {
            if (ModelState.IsValid)
            {
                Bicycle mainBicycle = new Bicycle(bicycle, tireWidth: bicycle.TireWidth, handlebarWidth: bicycle.HandlebarWidth);
                _mainService.BicycleService.UpdateBicycle(mainBicycle, compTrackChanges: false);
                _service.BicycleService.UpdateBicycle(bicycle, compTrackChanges: false);

                return RedirectToAction(nameof(Index));
            }

            return View(bicycle);
        }

        public IActionResult Details(int? id)
        {
            if (id == null || _service.BicycleService.GetAllBicycles() == null)
            {
                return NotFound();
            }

            var bicycle = _service.BicycleService.GetAllBicycles().FirstOrDefault(m => m.Id == id);

            if (bicycle == null)
            {
                return NotFound();
            }

            return View(bicycle);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || _service.BicycleService.GetAllBicycles() == null)
            {
                return NotFound();
            }

            var bicycle = _service.BicycleService.GetAllBicycles().FirstOrDefault(m => m.Id == id);

            if (bicycle == null)
            {
                return NotFound();
            }

            return View(bicycle);
        }

        [HttpPost, ActionName("Delete")]
        [IgnoreAntiforgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (_service.BicycleService.GetAllBicycles() == null)
            {
                return Problem("Entity set 'BicycleContext.Bicycle' is null");
            }

            _service.BicycleService.DeleteBicycle(id);
            _mainService.BicycleService.DeleteBicycle(id);

            return RedirectToAction(nameof(Index));
        }

        private static List<string> GetImagePath(int amount)
        {
            List<string> imagesPath = new List<string>();

            for (int i = 0; i < amount; i++)
            {
                int index = (i + 1) % 7;
                imagesPath.Add($"~/Images/gravel{index}.png");
            }

            return imagesPath;
        }
    }
}

BicycleApplication/Views/Characteristic/Electro.cshtml
<h3 style="text-align: center;">
    Електричний велосипед
</h3>
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Тип шасі</h5>
        </div>
        <p class="mb-1">Електричний велосипед: Електричні велосипеди оснащені електричним двигуном, який допомагає райдеру просуватися без зайвих зусиль. Вони можуть мати різні типи рами в залежності від призначення та стилю їзди.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Рама:</h5>
        </div>
        <p class="mb-1">Матеріал рами: Електричні велосипеди можуть мати рами з алюмінію, карбону або сталі, як і звичайні велосипеди. Вибір матеріалу залежить від призначення та бюджету.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Колеса:</h5>
        </div>
        <p class="mb-1">Розмір коліс: Електричні велосипеди можуть мати різний розмір коліс, зазвичай 26, 27.5 або 29 дюймів для гірських моделей і 700c для шосейних та міських варіантів.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Батарея:</h5>
        </div>
        <p class="mb-1">Ємність батареї: Електричні велосипеди оснащені літій-іонними батареями різної ємності. Велика ємність дозволяє проїздити більшу відстань на одному заряді, але може збільшувати вагу велосипеда.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Швидкість:</h5>
        </div>
        <p class="mb-1">Максимальна швидкість: Електричні велосипеди мають різну максимальну швидкість залежно від типу двигуна та регулювань. Деякі моделі можуть досягати швидкості до 25 км/год, в той час як інші можуть мати обмежену швидкість до 45 км/год.</p>
    </a>
</div>
<h3>
    <a asp-action="Index" asp-controller="ElectroBicycle">Побачити моделі</a>
</h3>

BicycleApplication/Views/Characteristic/Gravel.cshtml
<h3 style="text-align: center;">
    Гравійний велосипед
</h3>
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Тип шасі</h5>
        </div>
        <p class="mb-1">Гравійний велосипед: Велосипеди для гравійних доріг і бездоріжжя, як правило, мають жорстку раму і агресивний рульовий кут, що забезпечує краще керування на нерівних поверхнях.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Рама:</h5>
        </div>
        <p class="mb-1">Матеріал рами: Гравійні велосипеди можуть мати рами з алюмінію, карбону або сталі. Кожен матеріал має свої переваги, наприклад, алюмінієва рама є легкою і стійкою, карбонова рама має краще віброгасіння, а сталева рама дуже міцна та дешевша.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Колеса:</h5>
        </div>
        <p class="mb-1">Розмір коліс: Гравійні велосипеди часто мають колеса діаметром 700c, але також можуть використовувати колеса 650b для більшого обсягу шин на бездоріжжі. Колеса з невеликим профілем шини забезпечують хороше управління на дорозі та стабільність на бездоріжжі.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Передачі:</h5>
        </div>
        <p class="mb-1">Кількість передач: Гравійні велосипеди зазвичай оснащені трансмісіями з меншою кількістю передач, зазвичай від 1 до 11 швидкостей. Це дозволяє райдеру знаходити оптимальний ритм педалювання на різних ділянках маршруту та підйомах без зайвого зусилля.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Гальма:</h5>
        </div>
        <p class="mb-1">Тип гальм: Гравійні велосипеди можуть мати дискові гальма або ободні гальма. Дискові гальма забезпечують краще гальмування та контроль у всіх умовах, в той час як ободні гальма легші та простіші в обслуговуванні.</p>
    </a>
</div>
<h3>
    <a asp-action="Index" asp-controller="GravelBicycle">Побачити моделі</a>
</h3>

BicycleApplication/Views/Characteristic/Highway.cshtml
<h3 style="text-align: center;">
    Шосе велосипед
</h3>
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Тип шасі</h5>
        </div>
        <p class="mb-1">Призначення велосипедів для шосе: Велосипеди для шосе спеціально розроблені для швидкого пересування по асфальтованим дорогам. Вони мають легку конструкцію, жорстку раму і вузькі шини, що забезпечують найбільшу ефективність на асфальті.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Рама:</h5>
        </div>
        <p class="mb-1">Матеріал рами: Титанова, карбонова або алюмінієва рама. Титанові рами є легкими і міцними, карбонові рами дуже легкі і мають хорошу віброгасіння, алюмінієві рами легкі та відносно дешеві.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Колеса:</h5>
        </div>
        <p class="mb-1">Розмір коліс: Шосейні велосипеди зазвичай мають колеса діаметром 700с. Це розмір колеса, який забезпечує найбільшу ефективність на шосе.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Передачі:</h5>
        </div>
        <p class="mb-1">Кількість передач: Шосейні велосипеди зазвичай оснащені трансмісіями з великою кількістю передач, зазвичай від 16 до 22 швидкостей. Це дозволяє райдеру знаходити оптимальний ритм педалювання на різних ділянках шосе.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Гальма:</h5>
        </div>
        <p class="mb-1">Тип гальм: Шосейні велосипеди зазвичай мають ободні гальма або дискові гальма. Ободні гальма є легкими і простими для обслуговування, а дискові гальма забезпечують кращий контроль та гальмування у всіх умовах.</p>
    </a>
</div>
<h3>
    <a asp-action="Index" asp-controller="HighwayBicycle">Побачити моделі</a>
</h3>

BicycleApplication/Views/Characteristic/Mountain.cshtml
<h3 style="text-align: center;">
    Гірський велосипед
</h3>
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Тип шасі</h5>
        </div>
        <p class="mb-1">Жорстке шасі (Hardtail): Велосипеди з передньою амортизацією, але без задньої підвіски. Вони легші та ефективніше передають силу педалювання, але менш комфортні на нерівностях.</p>
        <p class="mb-1">Повністю підвішені (Full Suspension): Велосипеди з передньою і задньою амортизацією. Вони забезпечують краще поглинання ударів та краще тримання на нерівностях, але можуть бути важчими і менш ефективними при педалюванні на рівній дорозі.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Рама</h5>
        </div>
        <p class="mb-1">Матеріал рами: Алюмінієва, карбонова або сталева рама. Алюмінієві рами легкі та стійкі до корозії, карбонові рами краще поглинають вібрації та є дуже легкими, а сталеві рами мають високу міцність та довговічність.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Колеса</h5>
        </div>
        <p class="mb-1">Розмір коліс: Гірські велосипеди зазвичай мають колеса діаметром 27,5 або 29 дюймів. Колеса 29 дюймів забезпечують краще подолання перешкод і більшу стабільність на високих швидкостях, тоді як колеса 27,5 дюймів можуть бути більш маневреними.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Передачі</h5>
        </div>
        <p class="mb-1">Кількість передач: Гірські велосипеди можуть мати від 1 до 12 передач. Велика кількість передач забезпечує гнучкість у виборі швидкості та допомагає подолати різні умови траси, від крутого підйому до швидкого спуску.</p>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Призначення гірських велосипедів</h5>
        </div>
        <p class="mb-1">Крос-кантрі (XC): Легкі та швидкі велосипеди, призначені для швидкого пересування по гірських трасах та перегонів.</p>
        <p class="mb-1">Ендуро (Enduro): Велосипеди для агресивного катання на технічних трасах зі спусками.</p>
        <p class="mb-1">Фрірайд (Freeride): Велосипеди для екстремального катання на великих висотах із численними перешкодами.</p>
        <p class="mb-1">Даунхіл (Downhill): Велосипеди, спеціально розроблені для швидкого та агресивного спуску з гори.</p>
    </a>
</div>
<h3>
    <a asp-action="Index" asp-controller="MountainBicycle">Побачити моделі</a>
</h3>